puts "+ plus - addition"
puts "- minus - subtraction"
puts "/ slash - division"
puts "* asterisk - multiplication"
puts "% percentage - modulus"
puts "< less-than - less than something" 
puts "> greater-than - greater than something" 
puts "<= less-than-equal - less than or equal to"
puts ">= more-than-equal - more than or equal to" 
